version: '3'
services:
    python:
        restart: unless-stopped
        build: .
        command: /bin/bash -c "cd /app && alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 7000"
        ports:
            - "7000:7000"
        env_file: .env.docker
        links:
            - db
        depends_on:
            - db

    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev

        volumes:
            - postgres-data:/var/lib/postgresql/data


volumes:
    postgres-data: