"""extra fields for user model

Revision ID: 962d0a3415d8
Revises: 410dc934a43a
Create Date: 2024-03-06 15:47:24.476310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "962d0a3415d8"
down_revision: Union[str, None] = "410dc934a43a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("User", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "is_admin")
    op.drop_column("User", "phone")
    # ### end Alembic commands ###
