"""added all other models

Revision ID: 99396e86290f
Revises: 962d0a3415d8
Create Date: 2024-03-06 17:03:13.450401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99396e86290f"
down_revision: Union[str, None] = "962d0a3415d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Advert",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column("compensation", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("purchase", "sell", "service", name="adverttype"),
            nullable=False,
        ),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("advertiser_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["advertiser_id"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("advert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["advert_id"], ["Advert.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Complaint",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column("complainant_id", sa.Integer(), nullable=True),
        sa.Column("advert_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["advert_id"], ["Advert.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["complainant_id"], ["User.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Complaint")
    op.drop_table("Comment")
    op.drop_table("Advert")
    # ### end Alembic commands ###
