"""Added banned field to user

Revision ID: 9deca8cdf2bf
Revises: 52a8d2ef3cad
Create Date: 2024-03-08 14:47:42.602644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9deca8cdf2bf"
down_revision: Union[str, None] = "52a8d2ef3cad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "is_banned",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "is_banned")
    # ### end Alembic commands ###
